// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserEmail holds the string denoting the user_email field in the database.
	FieldUserEmail = "user_email"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldUserPassword holds the string denoting the user_password field in the database.
	FieldUserPassword = "user_password"

	// EdgeUserPredicament holds the string denoting the user_predicament edge name in mutations.
	EdgeUserPredicament = "user_predicament"

	// Table holds the table name of the user in the database.
	Table = "users"
	// UserPredicamentTable is the table the holds the user_predicament relation/edge.
	UserPredicamentTable = "predicaments"
	// UserPredicamentInverseTable is the table name for the Predicament entity.
	// It exists in this package in order to avoid circular dependency with the "predicament" package.
	UserPredicamentInverseTable = "predicaments"
	// UserPredicamentColumn is the table column denoting the user_predicament relation/edge.
	UserPredicamentColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserEmail,
	FieldUserName,
	FieldUserPassword,
}

var (
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// UserPasswordValidator is a validator for the "user_password" field. It is called by the builders before save.
	UserPasswordValidator func(string) error
)
