// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Predicament is the predicate function for predicament builders.
type Predicament func(*sql.Selector)

// Staff is the predicate function for staff builders.
type Staff func(*sql.Selector)

// Statuscar is the predicate function for statuscar builders.
type Statuscar func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
