app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:7000

organization:
  name: Acme Corporation

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'https:']
  database:
    client: sqlite3
    connection: ':memory:'

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs/docs
  generators:
    techdocs: 'docker'

lighthouse:
  baseUrl: http://localhost:3003

auth:
  providers: {}

scaffolder:
  github:
    token:
      $env: GITHUB_ACCESS_TOKEN
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]
  processors:
    github:
      providers:
        - target: https://github.com
          token:
            $env: GITHUB_PRIVATE_TOKEN
        # Example for how to add your GitHub Enterprise instance:
        # - target: https://ghe.example.net
        #   apiBaseUrl: https://ghe.example.net/api/v3
        #   token:
        #     $env: GHE_PRIVATE_TOKEN
  locations:
    # Backstage example components
    - type: url
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Backstage example APIs
    - type: url
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # Backstage example templates
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/springboot-grpc-template/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/docs-template/template.yaml
      rules:
        - allow: [Template]
