// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ambu/app/ent/car"
	"github.com/ambu/app/ent/predicament"
	"github.com/ambu/app/ent/schema"
	"github.com/ambu/app/ent/staff"
	"github.com/ambu/app/ent/statuscar"
	"github.com/ambu/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	carFields := schema.Car{}.Fields()
	_ = carFields
	// carDescCarNo is the schema descriptor for car_no field.
	carDescCarNo := carFields[0].Descriptor()
	// car.CarNoValidator is a validator for the "car_no" field. It is called by the builders before save.
	car.CarNoValidator = carDescCarNo.Validators[0].(func(string) error)
	predicamentFields := schema.Predicament{}.Fields()
	_ = predicamentFields
	// predicamentDescAddedTime is the schema descriptor for Added_Time field.
	predicamentDescAddedTime := predicamentFields[0].Descriptor()
	// predicament.DefaultAddedTime holds the default value on creation for the Added_Time field.
	predicament.DefaultAddedTime = predicamentDescAddedTime.Default.(func() time.Time)
	staffFields := schema.Staff{}.Fields()
	_ = staffFields
	// staffDescStaffName is the schema descriptor for staff_name field.
	staffDescStaffName := staffFields[1].Descriptor()
	// staff.StaffNameValidator is a validator for the "staff_name" field. It is called by the builders before save.
	staff.StaffNameValidator = staffDescStaffName.Validators[0].(func(string) error)
	// staffDescStaffPassword is the schema descriptor for staff_password field.
	staffDescStaffPassword := staffFields[2].Descriptor()
	// staff.StaffPasswordValidator is a validator for the "staff_password" field. It is called by the builders before save.
	staff.StaffPasswordValidator = staffDescStaffPassword.Validators[0].(func(string) error)
	statuscarFields := schema.Statuscar{}.Fields()
	_ = statuscarFields
	// statuscarDescStatusDetail is the schema descriptor for status_detail field.
	statuscarDescStatusDetail := statuscarFields[0].Descriptor()
	// statuscar.StatusDetailValidator is a validator for the "status_detail" field. It is called by the builders before save.
	statuscar.StatusDetailValidator = statuscarDescStatusDetail.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[1].Descriptor()
	// user.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
	// userDescUserPassword is the schema descriptor for user_password field.
	userDescUserPassword := userFields[2].Descriptor()
	// user.UserPasswordValidator is a validator for the "user_password" field. It is called by the builders before save.
	user.UserPasswordValidator = userDescUserPassword.Validators[0].(func(string) error)
}
