// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/ambu/app/ent/predicament"
	"github.com/ambu/app/ent/statuscar"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// StatuscarCreate is the builder for creating a Statuscar entity.
type StatuscarCreate struct {
	config
	mutation *StatuscarMutation
	hooks    []Hook
}

// SetStatusDetail sets the status_detail field.
func (sc *StatuscarCreate) SetStatusDetail(s string) *StatuscarCreate {
	sc.mutation.SetStatusDetail(s)
	return sc
}

// AddStatuscarPredicamentIDs adds the statuscar_predicament edge to Predicament by ids.
func (sc *StatuscarCreate) AddStatuscarPredicamentIDs(ids ...int) *StatuscarCreate {
	sc.mutation.AddStatuscarPredicamentIDs(ids...)
	return sc
}

// AddStatuscarPredicament adds the statuscar_predicament edges to Predicament.
func (sc *StatuscarCreate) AddStatuscarPredicament(p ...*Predicament) *StatuscarCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddStatuscarPredicamentIDs(ids...)
}

// Mutation returns the StatuscarMutation object of the builder.
func (sc *StatuscarCreate) Mutation() *StatuscarMutation {
	return sc.mutation
}

// Save creates the Statuscar in the database.
func (sc *StatuscarCreate) Save(ctx context.Context) (*Statuscar, error) {
	if _, ok := sc.mutation.StatusDetail(); !ok {
		return nil, &ValidationError{Name: "status_detail", err: errors.New("ent: missing required field \"status_detail\"")}
	}
	if v, ok := sc.mutation.StatusDetail(); ok {
		if err := statuscar.StatusDetailValidator(v); err != nil {
			return nil, &ValidationError{Name: "status_detail", err: fmt.Errorf("ent: validator failed for field \"status_detail\": %w", err)}
		}
	}
	var (
		err  error
		node *Statuscar
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StatuscarMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StatuscarCreate) SaveX(ctx context.Context) *Statuscar {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *StatuscarCreate) sqlSave(ctx context.Context) (*Statuscar, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *StatuscarCreate) createSpec() (*Statuscar, *sqlgraph.CreateSpec) {
	var (
		s     = &Statuscar{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: statuscar.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: statuscar.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.StatusDetail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: statuscar.FieldStatusDetail,
		})
		s.StatusDetail = value
	}
	if nodes := sc.mutation.StatuscarPredicamentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   statuscar.StatuscarPredicamentTable,
			Columns: []string{statuscar.StatuscarPredicamentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: predicament.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
