// Code generated by entc, DO NOT EDIT.

package car

const (
	// Label holds the string label denoting the car type in the database.
	Label = "car"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCarNo holds the string denoting the car_no field in the database.
	FieldCarNo = "car_no"

	// EdgeCarPredicament holds the string denoting the car_predicament edge name in mutations.
	EdgeCarPredicament = "car_predicament"

	// Table holds the table name of the car in the database.
	Table = "cars"
	// CarPredicamentTable is the table the holds the car_predicament relation/edge.
	CarPredicamentTable = "predicaments"
	// CarPredicamentInverseTable is the table name for the Predicament entity.
	// It exists in this package in order to avoid circular dependency with the "predicament" package.
	CarPredicamentInverseTable = "predicaments"
	// CarPredicamentColumn is the table column denoting the car_predicament relation/edge.
	CarPredicamentColumn = "carid"
)

// Columns holds all SQL columns for car fields.
var Columns = []string{
	FieldID,
	FieldCarNo,
}

var (
	// CarNoValidator is a validator for the "car_no" field. It is called by the builders before save.
	CarNoValidator func(string) error
)
