// Code generated by entc, DO NOT EDIT.

package statuscar

import (
	"github.com/ambu/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// StatusDetail applies equality check predicate on the "status_detail" field. It's identical to StatusDetailEQ.
func StatusDetail(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailEQ applies the EQ predicate on the "status_detail" field.
func StatusDetailEQ(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailNEQ applies the NEQ predicate on the "status_detail" field.
func StatusDetailNEQ(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailIn applies the In predicate on the "status_detail" field.
func StatusDetailIn(vs ...string) predicate.Statuscar {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statuscar(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatusDetail), v...))
	})
}

// StatusDetailNotIn applies the NotIn predicate on the "status_detail" field.
func StatusDetailNotIn(vs ...string) predicate.Statuscar {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statuscar(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatusDetail), v...))
	})
}

// StatusDetailGT applies the GT predicate on the "status_detail" field.
func StatusDetailGT(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailGTE applies the GTE predicate on the "status_detail" field.
func StatusDetailGTE(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailLT applies the LT predicate on the "status_detail" field.
func StatusDetailLT(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailLTE applies the LTE predicate on the "status_detail" field.
func StatusDetailLTE(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailContains applies the Contains predicate on the "status_detail" field.
func StatusDetailContains(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailHasPrefix applies the HasPrefix predicate on the "status_detail" field.
func StatusDetailHasPrefix(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailHasSuffix applies the HasSuffix predicate on the "status_detail" field.
func StatusDetailHasSuffix(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailEqualFold applies the EqualFold predicate on the "status_detail" field.
func StatusDetailEqualFold(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStatusDetail), v))
	})
}

// StatusDetailContainsFold applies the ContainsFold predicate on the "status_detail" field.
func StatusDetailContainsFold(v string) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStatusDetail), v))
	})
}

// HasStatuscarPredicament applies the HasEdge predicate on the "statuscar_predicament" edge.
func HasStatuscarPredicament() predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatuscarPredicamentTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatuscarPredicamentTable, StatuscarPredicamentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatuscarPredicamentWith applies the HasEdge predicate on the "statuscar_predicament" edge with a given conditions (other predicates).
func HasStatuscarPredicamentWith(preds ...predicate.Predicament) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatuscarPredicamentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatuscarPredicamentTable, StatuscarPredicamentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Statuscar) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Statuscar) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Statuscar) predicate.Statuscar {
	return predicate.Statuscar(func(s *sql.Selector) {
		p(s.Not())
	})
}
