/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersPredicament
 */
export interface ControllersPredicament {
    /**
     * 
     * @type {string}
     * @memberof ControllersPredicament
     */
    addedTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersPredicament
     */
    carID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPredicament
     */
    staffID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPredicament
     */
    statuscarID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersPredicament
     */
    userID?: number;
}

export function ControllersPredicamentFromJSON(json: any): ControllersPredicament {
    return ControllersPredicamentFromJSONTyped(json, false);
}

export function ControllersPredicamentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersPredicament {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'addedTime') ? undefined : json['addedTime'],
        'carID': !exists(json, 'carID') ? undefined : json['carID'],
        'staffID': !exists(json, 'staffID') ? undefined : json['staffID'],
        'statuscarID': !exists(json, 'statuscarID') ? undefined : json['statuscarID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersPredicamentToJSON(value?: ControllersPredicament | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedTime': value.addedTime,
        'carID': value.carID,
        'staffID': value.staffID,
        'statuscarID': value.statuscarID,
        'userID': value.userID,
    };
}


