/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCarEdges,
    EntCarEdgesFromJSON,
    EntCarEdgesFromJSONTyped,
    EntCarEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCar
 */
export interface EntCar {
    /**
     * CarNo holds the value of the "car_no" field.
     * @type {string}
     * @memberof EntCar
     */
    carNo?: string;
    /**
     * 
     * @type {EntCarEdges}
     * @memberof EntCar
     */
    edges?: EntCarEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntCar
     */
    id?: number;
}

export function EntCarFromJSON(json: any): EntCar {
    return EntCarFromJSONTyped(json, false);
}

export function EntCarFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'carNo': !exists(json, 'car_no') ? undefined : json['car_no'],
        'edges': !exists(json, 'edges') ? undefined : EntCarEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntCarToJSON(value?: EntCar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'car_no': value.carNo,
        'edges': EntCarEdgesToJSON(value.edges),
        'id': value.id,
    };
}


