/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCar,
    EntCarFromJSON,
    EntCarFromJSONTyped,
    EntCarToJSON,
    EntStaff,
    EntStaffFromJSON,
    EntStaffFromJSONTyped,
    EntStaffToJSON,
    EntStatuscar,
    EntStatuscarFromJSON,
    EntStatuscarFromJSONTyped,
    EntStatuscarToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPredicamentEdges
 */
export interface EntPredicamentEdges {
    /**
     * 
     * @type {EntCar}
     * @memberof EntPredicamentEdges
     */
    car?: EntCar;
    /**
     * 
     * @type {EntStaff}
     * @memberof EntPredicamentEdges
     */
    staff?: EntStaff;
    /**
     * 
     * @type {EntStatuscar}
     * @memberof EntPredicamentEdges
     */
    statuscar?: EntStatuscar;
    /**
     * 
     * @type {EntUser}
     * @memberof EntPredicamentEdges
     */
    user?: EntUser;
}

export function EntPredicamentEdgesFromJSON(json: any): EntPredicamentEdges {
    return EntPredicamentEdgesFromJSONTyped(json, false);
}

export function EntPredicamentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPredicamentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'car': !exists(json, 'Car') ? undefined : EntCarFromJSON(json['Car']),
        'staff': !exists(json, 'Staff') ? undefined : EntStaffFromJSON(json['Staff']),
        'statuscar': !exists(json, 'Statuscar') ? undefined : EntStatuscarFromJSON(json['Statuscar']),
        'user': !exists(json, 'User') ? undefined : EntUserFromJSON(json['User']),
    };
}

export function EntPredicamentEdgesToJSON(value?: EntPredicamentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'car': EntCarToJSON(value.car),
        'staff': EntStaffToJSON(value.staff),
        'statuscar': EntStatuscarToJSON(value.statuscar),
        'user': EntUserToJSON(value.user),
    };
}


