/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStaffEdges,
    EntStaffEdgesFromJSON,
    EntStaffEdgesFromJSONTyped,
    EntStaffEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStaff
 */
export interface EntStaff {
    /**
     * 
     * @type {EntStaffEdges}
     * @memberof EntStaff
     */
    edges?: EntStaffEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntStaff
     */
    id?: number;
    /**
     * StaffEmail holds the value of the "staff_email" field.
     * @type {string}
     * @memberof EntStaff
     */
    staffEmail?: string;
    /**
     * StaffName holds the value of the "staff_name" field.
     * @type {string}
     * @memberof EntStaff
     */
    staffName?: string;
    /**
     * StaffPassword holds the value of the "staff_password" field.
     * @type {string}
     * @memberof EntStaff
     */
    staffPassword?: string;
}

export function EntStaffFromJSON(json: any): EntStaff {
    return EntStaffFromJSONTyped(json, false);
}

export function EntStaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStaff {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntStaffEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'staffEmail': !exists(json, 'staff_email') ? undefined : json['staff_email'],
        'staffName': !exists(json, 'staff_name') ? undefined : json['staff_name'],
        'staffPassword': !exists(json, 'staff_password') ? undefined : json['staff_password'],
    };
}

export function EntStaffToJSON(value?: EntStaff | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntStaffEdgesToJSON(value.edges),
        'id': value.id,
        'staff_email': value.staffEmail,
        'staff_name': value.staffName,
        'staff_password': value.staffPassword,
    };
}


