/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntStatuscarEdges,
    EntStatuscarEdgesFromJSON,
    EntStatuscarEdgesFromJSONTyped,
    EntStatuscarEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStatuscar
 */
export interface EntStatuscar {
    /**
     * 
     * @type {EntStatuscarEdges}
     * @memberof EntStatuscar
     */
    edges?: EntStatuscarEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntStatuscar
     */
    id?: number;
    /**
     * StatusDetail holds the value of the "status_detail" field.
     * @type {string}
     * @memberof EntStatuscar
     */
    statusDetail?: string;
}

export function EntStatuscarFromJSON(json: any): EntStatuscar {
    return EntStatuscarFromJSONTyped(json, false);
}

export function EntStatuscarFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStatuscar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntStatuscarEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'statusDetail': !exists(json, 'status_detail') ? undefined : json['status_detail'],
    };
}

export function EntStatuscarToJSON(value?: EntStatuscar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntStatuscarEdgesToJSON(value.edges),
        'id': value.id,
        'status_detail': value.statusDetail,
    };
}


