/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntUserEdges,
    EntUserEdgesFromJSON,
    EntUserEdgesFromJSONTyped,
    EntUserEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUser
 */
export interface EntUser {
    /**
     * 
     * @type {EntUserEdges}
     * @memberof EntUser
     */
    edges?: EntUserEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntUser
     */
    id?: number;
    /**
     * UserEmail holds the value of the "user_email" field.
     * @type {string}
     * @memberof EntUser
     */
    userEmail?: string;
    /**
     * UserName holds the value of the "user_name" field.
     * @type {string}
     * @memberof EntUser
     */
    userName?: string;
    /**
     * UserPassword holds the value of the "user_password" field.
     * @type {string}
     * @memberof EntUser
     */
    userPassword?: string;
}

export function EntUserFromJSON(json: any): EntUser {
    return EntUserFromJSONTyped(json, false);
}

export function EntUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntUserEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userEmail': !exists(json, 'user_email') ? undefined : json['user_email'],
        'userName': !exists(json, 'user_name') ? undefined : json['user_name'],
        'userPassword': !exists(json, 'user_password') ? undefined : json['user_password'],
    };
}

export function EntUserToJSON(value?: EntUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntUserEdgesToJSON(value.edges),
        'id': value.id,
        'user_email': value.userEmail,
        'user_name': value.userName,
        'user_password': value.userPassword,
    };
}


