// Code generated by entc, DO NOT EDIT.

package staff

const (
	// Label holds the string label denoting the staff type in the database.
	Label = "staff"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStaffEmail holds the string denoting the staff_email field in the database.
	FieldStaffEmail = "staff_email"
	// FieldStaffName holds the string denoting the staff_name field in the database.
	FieldStaffName = "staff_name"
	// FieldStaffPassword holds the string denoting the staff_password field in the database.
	FieldStaffPassword = "staff_password"

	// EdgeStaffPredicament holds the string denoting the staff_predicament edge name in mutations.
	EdgeStaffPredicament = "staff_predicament"

	// Table holds the table name of the staff in the database.
	Table = "staffs"
	// StaffPredicamentTable is the table the holds the staff_predicament relation/edge.
	StaffPredicamentTable = "predicaments"
	// StaffPredicamentInverseTable is the table name for the Predicament entity.
	// It exists in this package in order to avoid circular dependency with the "predicament" package.
	StaffPredicamentInverseTable = "predicaments"
	// StaffPredicamentColumn is the table column denoting the staff_predicament relation/edge.
	StaffPredicamentColumn = "staffid"
)

// Columns holds all SQL columns for staff fields.
var Columns = []string{
	FieldID,
	FieldStaffEmail,
	FieldStaffName,
	FieldStaffPassword,
}

var (
	// StaffNameValidator is a validator for the "staff_name" field. It is called by the builders before save.
	StaffNameValidator func(string) error
	// StaffPasswordValidator is a validator for the "staff_password" field. It is called by the builders before save.
	StaffPasswordValidator func(string) error
)
